name: door_image

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [7]

task_name: &task_name door
dataset_type: &dataset_type ph
dataset_path: &dataset_path data/open_door/train_data.zarr
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.robosuite_image_runner.RobosuiteImageRunner

dataset:
  _target_: diffusion_policy.dataset.robosuite_image_dataset.RobosuiteImageDataset
  zarr_path: *dataset_path
  shape_meta: *shape_meta
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: False
  seed: 42
  val_ratio: 0.02
